### ISSUE TITLE
Various libmaple headers not found when compiling against latest STM_32 boards release

### ISSUE THREAD

**Issue by bakoontz2** [arpruss/USBComposite_stm32f1#116]
Errors all referring to STM32F1 headers not being found:

```
In file included from C:\Users\588673\Documents\Arduino\libraries\USBComposite/USBComposite.h:6,
                 from C:\Users\588673\Documents\AmateurRadio\VNA\VNA\VNA\flashstruct.cpp:28:
C:\Users\588673\Documents\Arduino\libraries\USBComposite/usb_generic.h:3:10: fatal error: libmaple/ibmaple_types.h: No such file or directory
    3 | #include <libmaple/libmaple_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```
I am running with version 0.91.  Here is the board setup:

![image](https://user-images.githubusercontent.com/38893590/180620052-3f9a2082-8af7-439e-ab08-87ae7cdd7999.png)

**Comment by arpruss** [comment]
I don't think you're using Roger's libmaple based core, but the official stm core (which is less efficient and not compatible with this library).

**Comment by bakoontz2** [comment]
So somehow I ended up installing the "official" STM core, which apparently overrides the libmaple core in typical random Arduino IDE fashion.  Deleting this "update" seems to have fixed the issue, sorry for the false alarm!
