### ISSUE TITLE
many joysticks in one stm32

### ISSUE THREAD

**Issue by vasilyman** [arpruss/USBComposite_stm32f1#14]
Can many xbox360 joysticks work in one stm32?

**Comment by vasilyman** [comment]
Will there be a wireless xbox360 ?

**Comment by arpruss** [comment]
I don't know anything about the wireless connections.

The library only supports one xbox controller at a time. It might be possible to extend it to support more than one, but it would require code changes. The easiest, but least elegant, way to add support for one more controller would be to make copies of usb_x360.* and USBXBox360.* and call them usb_x360b.* and USBXBox360b.* and replace all instances of "360" in the two files with "360b". 

The most elegant way would be to modify the generic device implementation to allow multiple instances of the same plugin type.  This would also solve https://github.com/arpruss/USBHID_stm32f1/issues/8

But doing this would increase memory usage for all users, and slightly decrease performance for all users.

**Comment by arpruss** [comment]
You could use the trick here: https://github.com/arpruss/GenesisToUSBDual

**Comment by arpruss** [comment]
I've just implemented USBMultiXBox360<n>, which allows up to 4 xbox 360 controllers.

I've tried to implement the wireless version, but I can't get Windows to recognize the data from it.

**Comment by arpruss** [comment]
Wireless is now implemented.

**Comment by vasilyman** [comment]
Wow! Great news!
