### ISSUE TITLE
Problem when compiling with new arduino ide

### ISSUE THREAD

**Issue by michalelektryk** [arpruss/USBComposite_stm32f1#18]
No meter which example i try i get this error message:

static_assert(sizeof(JoystickReport_t)==13, "Wrong endianness/packing!");

**Comment by arpruss** [comment]
Can you delete the static assert line from the code (I think it's in USBHID.h), and see if the SimpleJoystick example works?

**Comment by michalelektryk** [comment]
After removing static_assert I've got even more mistakes:
error: 'for' loop initial declarations are only allowed in C99 mode
for (unsigned i = 0 ; i < numParts ; i++) {

**Comment by arpruss** [comment]
You're going to have a lot of trouble if your IDE is configured not to have C99 mode on by default. Are you using Roger's core?

**Comment by arpruss** [comment]
Can you turn on C99 support?

**Comment by michalelektryk** [comment]
So i forced -std=c99 in compiler flags and i could get it to compile, i don't know why support isn't turned on by default. Thanks for your help and sorry for taking your time.
