### ISSUE TITLE
boards.h "no such file or directory"

### ISSUE THREAD

**Issue by xana43** [arpruss/USBComposite_stm32f1#19]
The boards.h that the entire library is referencing appears to be missing. From what i've checked it seems to be a capitalization error, changing #include boards.h to #include Boards.h in all the header files seems to fix it

**Comment by arpruss** [comment]
There must be something wrong with the core installation, because it is "boards.h" in https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/cores/maple

**Comment by xana43** [comment]
could be that it's not compatible with my board?

**Comment by arpruss** [comment]
What is your board?

**Comment by bakoontz2** [comment]
This appears to have been renamed "board.h" in the most recent STM_32 library found here:

https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
