### ISSUE TITLE
How to press GUI key?

### ISSUE THREAD

**Issue by steinm07** [arpruss/USBComposite_stm32f1#20]
Seriously, is this really not implemented?

**Comment by steinm07** [comment]
Yes, i have the key code... It's in one of the USBHID files.
BUT HOW DO I PRESS IT ON THE KEYBOARD?

**Comment by arpruss** [comment]
What kind of keyboard?

**Comment by arpruss** [comment]
I think it's probably the Windows key on Windows keyboards.
