### ISSUE TITLE
TwoJoysticks Example

### ISSUE THREAD

**Issue by Mozzytec** [arpruss/USBComposite_stm32f1#27]
Hi,
first of all congratulations for your job!! amazing and really usefull.
I tested the example provided and most of them works nicely.
Unfortunatly I tried the twojoystick.ino and it won't create the serial communication.
The Joysticks are well pointed. I can find them with a small utility and they work properly. BUT the serial port won't show up! no serial communication possible.
Any ideas around this?

I then try to add RawHid and joystick and again no way, it seems taht the descriptor is courruped when we add both. I need on joystick with a few buttons and the possibility to communicate (set ouptu) via either seerial or Raw. I would prefer Raw as no inf would then be needed.

**Comment by arpruss** [comment]
You need to add a CompositeSerial plugin to the device. See the readme file.
