### ISSUE TITLE
Midi in and Midi out in same component ?

### ISSUE THREAD

**Issue by AurelGTS** [arpruss/USBComposite_stm32f1#29]
Hello,

I m trying to create a midi in and out device. I can receive messages without problem. But I can't send messages. In usb_midi_tx function (usb_midi_device.c),  usb_midi_is_transmitting() always return true. So usb_midi_tx function do nothing... If you have an idea, I ll be thankful :)

Regards,
Aurélien

**Comment by soreau** [comment]
Maybe try `while(!writePackets());`
