### ISSUE TITLE
HID consumer and boot keyboard in same time?

### ISSUE THREAD

**Issue by FPeter84** [arpruss/USBComposite_stm32f1#40]
Hello! First, thanks for Your efforts! My problem is that the half of commands required by my remote controller project is listed in HID consumer category, other half is in boot keyboard mode... Is it possible to initialize them in the same project? I had no luck until now, they work well in separate project, but got blocked each time when i try to merge them... Do You have a working example for it?

**Comment by arpruss** [comment]
You have to make a HID report descriptor that includes both HID_CONSUMER_REPORT_DESCRIPTOR() and    HID_KEYBOARD_REPORT_DESCRIPTOR(). And then everything should just work. I added a ConsumerAndKeyboard example which should help you.
