### ISSUE TITLE
Buffer start address should have 2 bytes alignment as per reference manual.

### ISSUE THREAD

**Issue by victorpv** [arpruss/USBComposite_stm32f1#44]
https://github.com/arpruss/USBComposite_stm32f1/blob/90ab85438e5ddc98ab04e13ab1859b80f9ad7c8d/USBCompositeSerial.h#L40

This is regarding the discussion we had over the libmaple pma->buffer copy functions. As per STM reference manual buffer size ( and buffer start position) should have 8 byte alignments. Just wanted to make the note here in the part that sets the buffer size.

EDIT: I see similar functions in MIDI:
https://github.com/arpruss/USBComposite_stm32f1/blob/4dfa0e825cad6b3126cb139425b552876770fa4f/USBMIDI.h#L124-L130

**Comment by arpruss** [comment]
Are we talking about alignment of PMA buffers here?

**Comment by victorpv** [comment]
Yes

**Comment by arpruss** [comment]
It's a bit more complicated by my reading of the reference manual: if the size of the buffer is less than 64 bytes, the length must be even; if the size of the buffer is 64 bytes or more, it must be divisible by 32.  I fixed this in the abstracted branch, which soon will supercede master.

**Comment by victorpv** [comment]
Even more complicated from what I see, the 2 / 32 multiplier thing only applies to the RX buffers, but not the TX...
Glad that you figured it out.

**Comment by arpruss** [comment]
Yeah. I'll revert for tx.
I'm now dealing with an odd issue where serial fails unless the buffer size is a power of 2.
