### ISSUE TITLE
Add Xbox One Dongle Compatibility

### ISSUE THREAD

**Issue by hppyrbt** [arpruss/USBComposite_stm32f1#60]
Hi. Would it be possible to add compatibility for the Xbox One receiver dongle?
I'm really interested in being able to read data from an xbox one controller wirelessly. However, I don't have the knowledge to do it on my own.
It seems to me that doing it with the dongle (the large version of the dongle) would give better results than with bluetooth, because the dongle seems to have 3 antennas and a robust and good design.

I could help by donating some dongle so that compatibility could be added.
I would appreciate it too much. Thanks in advance.

**Comment by arpruss** [comment]
This library emulates USB devices, not USB hosts. If you want to talk to the dongle, you need USB host capabilities. If you want to emulate the dongle, this library can do that.
