### ISSUE TITLE
STM32F401 compatibility

### ISSUE THREAD

**Issue by ribastudio** [arpruss/USBComposite_stm32f1#61]
Hi!

We developing a project with STM32F103 using this library. For some limitations, we would like to use a STM32F401, but's library it's not compatible. We observe no one Midi arduino libraries are compatible with this F401 chip. Have a any type of hook, or adaptation we can make to solve this? Any light to these question?

**Comment by arpruss** [comment]
You would need to port the usb_generic.c code. Everything else is built on that and should be largely hardware independent.
