### ISSUE TITLE
How to change MIDI device source name from Maple?

### ISSUE THREAD

**Issue by 3gyptian** [arpruss/USBComposite_stm32f1#65]
My composite MIDI device is working perfectly however I'd like to change how it displays on the host as something different than Maple.  I've searched the library header files and elsewhere looking where this might be defined to no avail.  

Such a great library this is.  Thank you!

**Comment by arpruss** [comment]
```
USBComposite.setVendorId(uint16 vendor);
USBComposite.setProductId(uint16 product);
USBComposite.setManufacturerString(const char* manufacturer);
USBComposite.setProductString(const char* product);
USBComposite.setSerialString(const char* serialNumber);
```

Windows may still show the old name if you just change the name without changing either the product or the vendor id.

**Comment by 3gyptian** [comment]
That totally worked for me.  Thanks man!!!
