### ISSUE TITLE
boards.h: No such file or directory

### ISSUE THREAD

**Issue by mentaluproar** [arpruss/USBComposite_stm32f1#75]
When attempting to use this library on an SKR E3-DIP 3d printer control board, set as a genericSTM32F103RC board, I get the missing file error in the title.  No boards.h file.  I figured I would have to configure this board somewhere but there's no boards.h file to modify.

**Comment by arpruss** [comment]
I remember such a report. I think the person wasn't using the official Arduino IDE.

**Comment by mentaluproar** [comment]
Oh sorry, I am using platformIO.  I wasn't able to get the Arduino IDE to do anything with this control board.

**Comment by arpruss** [comment]
See: https://www.instructables.com/id/Gamecube-Controller-USB-Adapter-and-Getting-Starte/

**Comment by BrianHarper** [comment]
I have a ST-link v2 and "bluepill), trying to program with Arduino 1.8.11 and the latest STM32 cores board config. But when trying to compile the MidiPotentiometer.ino I'm getting the following:-  
Arduino: 1.8.11 (Windows 7), TD: 1.51, Board: "Generic STM32F1 series, BluePill F103C8, STM32CubeProgrammer (SWD), Enabled (generic 'Serial'), HID (keyboard and mouse), Low/Full Speed, Smallest (-Os default), Newlib Nano (default)"

In file included from C:\Users\user\Desktop\arduino-1.8.11\portable\sketchbook\libraries\USBComposite_stm32f1-master\examples\MidiPotentiometer\MidiPotentiometer.ino:1:
C:\Users\user\Desktop\arduino-1.8.11\portable\sketchbook\libraries\USBComposite_stm32f1-master/USBComposite.h:4:10: fatal error: boards.h: No such file or directory
    4 | #include <boards.h>
      |          ^~~~~~~~~~
compilation terminated.

exit status 1
Error compiling for board Generic STM32F1 series.

Could some one plese point me in the right direction as to what I am missing.
Thanks....

**Comment by arpruss** [comment]
Are you using platformIO?

**Comment by BrianHarper** [comment]
> 
> 
> Are you using platformIO?

No, using the Arduino 1.8.11 IDE

**Comment by arpruss** [comment]
Looking at your error message, I think you're not using Roger's libmaple based core.

**Comment by BrianHarper** [comment]
No I don't have that installed, just the standard "stm32 cores". do I need Roger's libmaple based core as well,  or instead of what I already have installed

**Comment by arpruss** [comment]
This library is not compatible with the stm supplied core. You need the libmaple core instead.

**Comment by BrianHarper** [comment]
Yes just installed a seperate portable IDE and installed the libmaple core and managed to get it working, Thanks for your help.
Now to build a USB Midi CC controller.....
