### ISSUE TITLE
Keyboard and multiple serial ports

### ISSUE THREAD

**Issue by Tima32** [arpruss/USBComposite_stm32f1#82]
Can I use a keyboard and multiple serial ports?
How do I choose a frequency serial port?
https://github.com/arpruss/USBComposite_stm32f1/blob/master/examples/keyboardwithleds/keyboardwithleds.ino

**Comment by arpruss** [comment]
See the ENDPOINT LIMITATIONS section of the README. And note that MultiSerial may have some Linux issues.
There is no frequency for USB serial. It's an emulated serial.
