### ISSUE TITLE
PitchBend is a channel command

### ISSUE THREAD

**Issue by MicroBahner** [arpruss/USBComposite_stm32f1#83]
Hello,
as far as I know, the pitch bend command is a channel command. But sendPitchChange() doesn't allow to define a channel, and handlePitchChange() doesn't return the channel information.
In my opinion this an error ( which could be fixed easily ;) ).
Regards
Franz-Peter

**Comment by arpruss** [comment]
I don't know much about MIDI. Can you make a fix and test it?

**Comment by MicroBahner** [comment]
I have already made the appropriate changes for my application. I will test a little more and then make a suggestion.
Franz-Peter

**Comment by MicroBahner** [comment]
I created a pull-request with the necessary changes to add the channel info to the read/write methods for pitch bend.

**Comment by arpruss** [comment]
Thank you!
