### ISSUE TITLE
How to use the original keyboard keycodes?

### ISSUE THREAD

**Issue by Tima32** [arpruss/USBComposite_stm32f1#88]
How to use the original keyboard keycodes?
If there is no such function, I would like it to appear.

**Comment by arpruss** [comment]
Do you mean the USB HID usage codes in Table 12 here: https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf ?

**Comment by Tima32** [comment]
Yes.
I solved this problem by removing this line:
`k = getKeyCode(k, &modifiers);`
Haven't done a full test yet, but it seems to work.
But I still want to get official support.

There is a newer and more convenient table:
https://www.usb.org/sites/default/files/hut1_21_0.pdf
